import type { Metadata } from 'next'
import Link from 'next/link'
import '../globals.css'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function LearnerLayout({
   children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className="h-[100vh] bg-gray-300">
                <div className="flex flex-row bg-white mx-24 p-12 rounded-b-2xl">
                    <Link href="/home" className="font-bold text-3xl">OpenLMS</Link>
                    <div className="flex ml-auto space-x-10 text-2xl">
                        <Link href="/profile">View Profile</Link>
                        {/*TODO - conditional rendering for admin-users to see "platform tools" option*/}
                        <Link href="/">Log Out</Link>
                    </div>
                </div>
                {children}
            </body>
        </html>
    )
}
