export enum CourseStatus {
    NOT_ENROLLED = "NOT_ENROLLED",
    ENROLLED = "ENROLLED",
    IN_PROGRESS = "IN_PROGRESS",
    AWAITING_MARKING = "AWAITING_MARKING",
    FAILED = "FAILED",
    COMPLETED = "COMPLETED"
}

export enum QuestionType {
    MULTIPLE_CHOICE = "MC",
    TRUE_FALSE = "TF",
    SHORT_ANSWER = "SA"
}
