import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function AdminLayout({
   children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className="h-[100vh]">
                <div className="flex flex-row bg-white mx-24 p-12 rounded-b-2xl">
                    <Link href="/learner" className="font-bold text-3xl">OpenLMS</Link>
                    <div className="flex ml-auto space-x-10 text-2xl">
                        <Link href="/admin/profile">View Profile</Link>
                        <Link href="/admin/tools">Platform Tools</Link>
                        <Link href="/">Log Out</Link>
                    </div>
                </div>
                {children}
            </body>
        </html>
    )
}
