name: CI - Full test suite

on:
  pull_request:
    branches:
      - "**"

jobs:
    test:
        runs-on: ubuntu-latest
        environment: Production
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Setup pnpm
            uses: pnpm/action-setup@v4
            with:
              version: 9.5.0
          - name: Setup node
            uses: actions/setup-node@v4
            with:
              node-version: 20.x
              cache: 'pnpm'
          - name: Install dependencies
            run: pnpm install --frozen-lockfile
          - name: Install global test tools
            run: pnpm install -g mocha ts-node
          - name: Deploy API to test
            env:
              TEST_SUPABASE_REF: ${{ secrets.TEST_SUPABASE_REF }}
              SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
            run: pnpm run deployTest

          - name: Run detailed tests
            env:
              NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
              NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}

              TEST_SUPABASE_URL: ${{ secrets.TEST_SUPABASE_URL }}
              TEST_SUPABASE_ANON_KEY: ${{ secrets.TEST_SUPABASE_ANON_KEY }}
              TEST_SUPABASE_REF: ${{ secrets.TEST_SUPABASE_REF }}

              TEST_ADMIN_EMAIL: ${{ secrets.TEST_ADMIN_EMAIL }}
              TEST_ADMIN_PASSWORD: ${{ secrets.TEST_ADMIN_PASSWORD }}
              TEST_LEARNER_EMAIL: ${{ secrets.TEST_LEARNER_EMAIL }}
              TEST_LEARNER_PASSWORD: ${{ secrets.TEST_LEARNER_PASSWORD }}
            run: pnpm run test:detailed
