name: CI - Sanity

on:
  push:
    branches:
      - "**"

jobs:
    test:
        runs-on: ubuntu-latest
        environment: Production
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Setup pnpm
            uses: pnpm/action-setup@v4
            with:
              version: 9.5.0
          - name: Setup node
            uses: actions/setup-node@v4
            with:
              node-version: 20.x
              cache: 'pnpm'
          - name: Install dependencies
            run: pnpm install --frozen-lockfile
          - name: Install global test tools
            run: pnpm install -g mocha ts-node

          - name: Run sanity tests
            run: pnpm run test:sanity
