/**
 * Create database tables
 */

-- High-level course info (name, link, description, etc)
CREATE TABLE
    public.course (
                      id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,

                      user_id UUID NOT NULL,

                      name TEXT NOT NULL,
                      description TEXT,
                      link TEXT,
                      active BOOLEAN DEFAULT TRUE,
                      version INT DEFAULT 1,
                      min_time INT,

                      max_quiz_attempts INT,
                      min_quiz_score INT,
                      preserve_quiz_question_order BOOLEAN,
                      quiz_time_limit INT,
                      total_quiz_marks INT,
                      num_quiz_questions INT,

                      FOREIGN KEY (user_id) REFERENCES auth.users(id)
);

-- Quiz questions for courses with quizzes
CREATE TABLE
    public.quiz_question (
                             id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,

                             course_id INT NOT NULL,
                             question_order INT, -- Order within the quiz

                             question TEXT NOT NULL,
                             marks INT NOT NULL,
                             type CHAR(2) NOT NULL CHECK (type IN ('MC', 'TF', 'SA')),
                             correct_answer INT,
                             answers JSON,

    -- Stats for this question: How many of each answer have been submitted e.g: { "Ontario": 2, "Alberta": 1 }
                             submitted_answers JSON NOT NULL DEFAULT '{}',

                             FOREIGN KEY (course_id) REFERENCES public.course(id)
);

-- Keeps track of which courses users are enrolled in
CREATE TABLE
    public.enrolled_course (
                               user_id uuid NOT NULL,
                               course_id INT NOT NULL,

                               status TEXT NOT NULL DEFAULT 'ENROLLED',

                               enrollment_time TIMESTAMPTZ DEFAULT NOW() NOT NULL,

                               PRIMARY KEY (user_id, course_id),
                               FOREIGN KEY (user_id) REFERENCES auth.users(id),
                               FOREIGN KEY (course_id) REFERENCES public.course(id)
);

-- Attempts by users at courses (may be multiple per course)
CREATE TABLE
    public.course_attempt (
                              id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                              course_id INT NOT NULL,
                              user_id UUID NOT NULL,

                              pass BOOLEAN,
                              start_time TIMESTAMPTZ DEFAULT NOW() NOT NULL,
                              end_time TIMESTAMPTZ,

                              FOREIGN KEY (course_id) REFERENCES public.course(id),
                              FOREIGN KEY (user_id) REFERENCES auth.users(id)
);

-- Attempts at a course's quiz by a user (may be multiple per course attempt)
CREATE TABLE
    public.quiz_attempt (
                            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                            course_id INT NOT NULL,
                            user_id UUID NOT NULL,
                            course_attempt_id INT NOT NULL,

                            pass BOOLEAN,
                            start_time TIMESTAMPTZ DEFAULT NOW() NOT NULL,
                            end_time TIMESTAMPTZ,
                            score INT,

                            marker_id UUID,
                            marking_time TIMESTAMPTZ,

                            FOREIGN KEY (course_id) REFERENCES public.course(id),
                            FOREIGN KEY (user_id) REFERENCES auth.users(id),
                            FOREIGN KEY (course_attempt_id) REFERENCES public.course_attempt(id)
);

-- Attempts for each individual question, as there are often many per quiz
CREATE TABLE
    public.quiz_question_attempt (
                                     id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                     course_id INT NOT NULL,
                                     user_id UUID NOT NULL,
                                     quiz_question_id INT NOT NULL,
                                     course_attempt_id INT NOT NULL,
                                     quiz_attempt_id INT NOT NULL,

                                     type CHAR(2) NOT NULL CHECK (type IN ('MC', 'TF', 'SA')), -- Helper

                                     response TEXT NOT NULL, -- For numerical responses, this is the answer number as a string (e.g. "2")
                                     max_marks INT NOT NULL,
                                     marks_achieved INT, -- Can be null if it's a short answer and hasn't been marked yet

                                     FOREIGN KEY (course_id) REFERENCES public.course(id),
                                     FOREIGN KEY (user_id) REFERENCES auth.users(id),
                                     FOREIGN KEY (quiz_question_id) REFERENCES public.quiz_question(id),
                                     FOREIGN KEY (course_attempt_id) REFERENCES public.course_attempt(id),
                                     FOREIGN KEY (quiz_attempt_id) REFERENCES public.quiz_attempt(id)
);

-- Notification for various events (new courses, quiz marked, etc)
CREATE TABLE
    public.notification (
                            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                            user_id UUID NOT NULL,
                            date TIMESTAMPTZ DEFAULT NOW() NOT NULL,

                            direct BOOLEAN NOT NULL,
                            title TEXT NOT NULL,
                            link TEXT,
                            read BOOLEAN NOT NULL DEFAULT FALSE,

                            FOREIGN KEY (user_id) REFERENCES auth.users(id)
);

CREATE TABLE
    public.error_log (
                         id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                         timestamp TIMESTAMPTZ DEFAULT NOW() NOT NULL,
                         request_uuid UUID,
                         endpoint TEXT,
                         type TEXT NOT NULL,
                         request_user_id UUID,
                         payload JSON,

                         message TEXT NOT NULL,
                         stack_trace TEXT,

                         FOREIGN KEY (request_user_id) REFERENCES auth.users(id)
);
